#########get
POST http://localhost:4004/odata/v4/PurchaseApproval/datafrombpa
Content-Type: application/json

{
  "status": "A",
  "requestid": "14"
}

###get
POST http://localhost:4004/odata/v4/PurchaseApproval/approveRequest
Content-Type: application/json

{
  "requestid": "13"
}
###get
POST http://localhost:4004/odata/v4/PurchaseApproval/rejectRequest
Content-Type: application/json

{
  "requestid": "13"
}
#####
POST http://localhost:4004/odata/v4/PurchaseApproval/sendforapproval
Content-Type: application/json

{
}


### Test choosing approver for total price greater than 50000
GET http://localhost:4004/odata/v4/PurchaseApproval/approverSelection
Content-Type: application/json
 
{
    "totalPrice": 15000
}